export const HOME_GET = 'HOME_GET';
export const HOME_GET_SUCCESS = 'HOME_GET_SUCCESS';
export const COLLECTIONS_GET = 'COLLECTIONS_GET';
export const COLLECTIONS_GET_SUCCESS = 'COLLECTIONS_GET_SUCCESS';
export const SETS_GET = 'SETS_GET';
export const SETS_GET_SUCCESS = 'SETS_GET_SUCCESS';
