export const HOME_GET = 'HOME_GET';
export const HOME_GET_SUCCESS = 'HOME_GET_SUCCESS';
export const PAINTINGS_GET = 'PAINTINGS_GET';
export const PAINTINGS_GET_SUCCESS = 'PAINTINGS_GET_SUCCESS';
export const DRAWINGS_GET = 'DRAWINGS_GET';
export const DRAWINGS_GET_SUCCESS = 'DRAWINGS_GET_SUCCESS';
export const SCULPTURES_GET = 'SCULPTURES_GET';
export const SCULPTURES_GET_SUCCESS = 'SCULPTURES_GET_SUCCESS';
